Repository tmax-cloud/hypercloud-sds, pull requests merged in 2020-12, with the labels that each got.

#30 Fix github action bugs
  .github/workflows/hcsctl.yml
  hcsctl/e2e/cdi/cdi_test.go
Labels: bug

#33 Github Action Bugfix
  .github/workflows/hcsctl.yml
Labels: bug

#34 Update golangci-lint version
  .github/workflows/hcsctl.yml
Labels: bug

#32 fix toolbox upgrade guide
  docs/upgrade/README.md
Labels: bug

#35 Apply [skip-ci]
  .github/workflows/hcsctl.yml
Labels: ci/cd

#36 Apply [skip-ci]
  .github/workflows/hcsctl.yml
Labels: ci/cd

#37 Apply [skip-ci]
  .github/workflows/hcsctl.yml
Labels: ci/cd

#38 add v1.4 toolbox yaml to upgrade docs
  docs/upgrade/7_toolbox.yaml
  docs/upgrade/README.md
Labels: documentation

#39 Update k8s version for e2e test environment
  .github/workflows/hcsctl.yml
  hack/prolinux_cluster.sh
Labels: ci/cd

#40 Change create to apply in upgrade docs
  docs/upgrade/README.md
Labels: documentation
